#This file is an example of an environment file for defining the isolated
#networks and related parameters.
#resource_registry:
#  # Network Interface templates to use (these files must exist)
#  OS::TripleO::BlockStorage::Net::SoftwareConfig: ../network/config/single-nic-vlans/cinder-storage.yaml
#  OS::TripleO::Compute::Net::SoftwareConfig: ../network/config/single-nic-vlans/compute.yaml
#  OS::TripleO::Controller::Net::SoftwareConfig: ../network/config/single-nic-vlans/controller.yaml
#  OS::TripleO::ObjectStorage::Net::SoftwareConfig: ../network/config/single-nic-vlans/swift-storage.yaml
#  OS::TripleO::CephStorage::Net::SoftwareConfig: ../network/config/single-nic-vlans/ceph-storage.yaml

resource_registry:
  OS::TripleO::BlockStorage::Net::SoftwareConfig: /home/stack/templates/nic-configs/cinder-storage.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: /home/stack/templates/nic-configs/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/templates/nic-configs/controller.yaml
  OS::TripleO::ObjectStorage::Net::SoftwareConfig: /home/stack/templates/nic-configs/swift-storage.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig: /home/stack/templates/nic-configs/ceph-storage.yaml
  OS::TripleO::NodeUserData: /home/stack/templates/wipe_disks.yaml

#parameter_defaults:
#  InternalApiNetCidr: 172.17.0.0/24
#  StorageNetCidr: 172.18.0.0/24
#  StorageMgmtNetCidr: 172.19.0.0/24
#  TenantNetCidr: 172.16.0.0/24
#  ExternalNetCidr: 10.0.0.0/24
#  ControlPlaneSubnetCidr: '24'
#  InternalApiAllocationPools: [{'start': '172.17.0.10', 'end': '172.17.0.200'}]
#  StorageAllocationPools: [{'start': '172.18.0.10', 'end': '172.18.0.200'}]
#  StorageMgmtAllocationPools: [{'start': '172.19.0.10', 'end': '172.19.0.200'}]
#  TenantAllocationPools: [{'start': '172.16.0.10', 'end': '172.16.0.200'}]
#  ExternalAllocationPools: [{'start': '10.0.0.10', 'end': '10.0.0.50'}]
#  ExternalInterfaceDefaultRoute: 10.0.0.1
#  ControlPlaneDefaultRoute: 192.0.2.254
#  EC2MetadataIp: 192.0.2.1
#  DnsServers: ["8.8.8.8","8.8.4.4"]
#  InternalApiNetworkVlanID: 10
#  StorageNetworkVlanID: 20
#  StorageMgmtNetworkVlanID: 30
#  TenantNetworkVlanID: 40
#  ExternalNetworkVlanID: 50
#  NeutronExternalNetworkBridge: "''"
#  BondInterfaceOvsOptions: "mode=active-backup"

parameter_defaults:
  InternalApiNetCidr: 172.16.0.0/24
  TenantNetCidr: 172.17.0.0/24
  StorageNetCidr: 172.18.0.0/24
  StorageMgmtNetCidr: 172.19.0.0/24
  ManagementNetCidr: 172.20.0.0/24
  ExternalNetCidr: 10.1.1.0/24
  InternalApiAllocationPools: [{'start': '172.16.0.10', 'end': '172.16.0.200'}]
  TenantAllocationPools: [{'start': '172.17.0.10', 'end': '172.17.0.200'}]
  StorageAllocationPools: [{'start': '172.18.0.10', 'end': '172.18.0.200'}]
  StorageMgmtAllocationPools: [{'start': '172.19.0.10', 'end': '172.19.0.200'}]
  ManagementAllocationPools: [{'start': '172.20.0.10', 'end': '172.20.0.200'}]
  ExternalAllocationPools: [{'start': '10.1.1.100', 'end': '10.1.1.150'}]
  ExternalInterfaceDefaultRoute: 10.1.1.1
  ControlPlaneDefaultRoute: 192.0.2.1
  EC2MetadataIp: 192.0.2.1
  DnsServers: ["8.8.8.8","8.8.4.4"]
  InternalApiNetworkVlanID: 201
  TenantNetworkVlanID: 202
  StorageNetworkVlanID: 203
  StorageMgmtNetworkVlanID: 204
  ManagementNetworkVlanID: 205
  ExternalNetworkVlanID: 100
